
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// `prisma generate` / `prisma validate` never connect to the database, so a
// missing DATABASE_URL must not fail the build (e.g. the Railway frontend
// service, which only sets NEXT_PUBLIC_API_URL). Fall back to a dummy local
// path; real commands (`db push`, the running server) always receive the real
// DATABASE_URL from the environment or apps/backend/.env.
const databaseUrl = process.env.DATABASE_URL?.trim() || "file:./dev.db";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
  },
});
